### ISSUE TITLE
mpesm missing lsh_sims requirement / import / doc

### ISSUE THREAD

**Issue by arbor-jjones** [carbonblack/tic#1]
Didn't find anything in the related docs / readme / requirements on lsh_sims and unsure which module this refers to, possibly the one from click's data hacking repository going on the module/class name?

    python mpesm.py -s mpesm.sig ~/Downloads/d249ebd4fbd161ebd3b33ef2fd5aedf3
    global name 'lsh_sims' is not defined

**Comment by sooshie** [comment]
Sorry, removed the stale code.
